version: "3"

services:
  proxy:
    image: traefik:1.7.19
    container_name: traefik
    networks:
      - traefik
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./config:/etc/traefik"
    restart: unless-stopped
    command:
      - --accessLog
      - --logLevel=INFO
      - --defaultEntryPoints=http,https
      - --entryPoints=Name:http Address::80 #Redirect.EntryPoint:https
      - --entryPoints=Name:https Address::443 TLS TLS.DefaultCertificate.Cert:/etc/traefik/ssl/server.crt  TLS.DefaultCertificate.Key:/etc/traefik/ssl/server.key
      - --docker.endpoint=unix:///var/run/docker.sock
      - --docker.domain=${TRAEFIK_DOMAIN}
      - --docker.watch=true
      - --docker.exposedbydefault=false
      - --web
      - --web.address=:8080
      - --acme
      - --acme.email=${TRAEFIK_EMAIL}
      - --acme.storage=/etc/traefik/acme.json
      - --acme.entryPoint=https
      - --acme.httpchallenge.entrypoint=http
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:${TRAEFIK_DOMAIN}"
      - "traefik.frontend.entryPoints=http, https"
      - "traefik.frontend.redirect.entryPoint=https"
      - "traefik.frontend.redirect.permanent=true"
      - "traefik.frontend.auth.basic.users=admin:$$apr1$$o1HmXW0i$$wWgVewL1kLu9gaqmMDh6u/"
      - "traefik.port=8080"
      - "traefik.backend=traefik"

networks:
  traefik:
    external:
      name: traefik
